<?php
/**
 * Plugin Name: WP Social Aggregator
 * Description: Aggregate Facebook, Instagram, Twitter and LinkedIn feeds into one shortcode. Supports source URLs, embed HTML and optional API keys.
 * Version: 0.1.0
 * Author: Generated by Copilot
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

define( 'WSA_PATH', plugin_dir_path( __FILE__ ) );
define( 'WSA_URL', plugin_dir_url( __FILE__ ) );

require_once WSA_PATH . 'includes/admin.php';
require_once WSA_PATH . 'includes/providers.php';
require_once WSA_PATH . 'includes/public.php';

register_activation_hook( __FILE__, 'wsa_activate' );
function wsa_activate() {
    if ( false === get_option( 'wsa_settings' ) ) {
        $defaults = array(
            'twitter_sources' => '',
            'twitter_embed'   => '',
            'twitter_api_key' => '',
            'instagram_sources' => '',
            'instagram_embed'   => '',
            'instagram_api_key' => '',
            'facebook_sources' => '',
            'facebook_embed'   => '',
            'facebook_api_key' => '',
            'linkedin_sources' => '',
            'linkedin_embed'   => '',
            'linkedin_api_key' => '',
        );
        add_option( 'wsa_settings', $defaults );
    }
}

// Enqueue frontend styles
add_action( 'wp_enqueue_scripts', function(){
    wp_register_style( 'wsa-style', WSA_URL . 'assets/css/wsa-style.css' );
    wp_enqueue_style( 'wsa-style' );
} );
